//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_EasyX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor : AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Bookings = new HashSet<Bookings>();
        }

        public Doctor(AspNetUsers aspNetUsers, Doctor doctor)
        {
            foreach (var prop in aspNetUsers.GetType().GetProperties())
            {
                this.GetType().GetProperty(prop.Name).SetValue(this, prop.GetValue(aspNetUsers, null), null);
            }
            this.Title = doctor.Title;
            this.First_Name = doctor.First_Name;
            this.Last_Name = doctor.Last_Name;
            this.Major = doctor.Major;
            this.Address = doctor.Address;
            this.Is_Ready_For_Visitor = doctor.Is_Ready_For_Visitor;
            this.Bookings = new HashSet<Bookings>();
        }
        [Required(ErrorMessage = "Title cannot be empty.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "First Name cannot be empty.")]
        [Display(Name = "First Name")]

        public string First_Name { get; set; }
        [Required(ErrorMessage = "Last Name cannot be empty.")]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "Major cannot be empty.")]

        public string Major { get; set; }
        [Required(ErrorMessage = "Address cannot be empty.")]

        public string Address { get; set; }
        public bool Is_Ready_For_Visitor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
    }
}
